### ISSUE TITLE
Nice Job, aber

### ISSUE THREAD

**Issue by Stefanmelz** [slashworks/contao-starter-bundle#1]
Noch cooler wäre, wenn wir gleich ne Websitebasierte Extension anlegen mit Basisordnern. also /src/AppBundle und den ganzen ressource krams. Wieder nachlesen gespart 👯‍♂

**Comment by sgruna** [comment]
Guter Hinweis.

Ich habe den src/AppBundle-Ordner in der neusten Version integriert. Enthalten sind einige Basis-Ordner und PHP-Dateien, die oft verwendet werden. Zusätzlich stehen in README-Dateien Hinweise zur einheitlichen Verwendung der Klassen und Namespaces.

Bei Verwendung der composer.json aus der [Contao Starter Edition](https://github.com/slashworks/contao-starter-edition) wird das AppBundle automatisch registriert.
Bei einem nachträglichen Update des Contao-Starter-Bundles muss der Eintrag manuell in der root composer.json eingefügt werden:
```json
"autoload": {
    "psr-4": {
        "AppBundle\\": "src/AppBundle/"
    }
},
```
