### ISSUE TITLE
Über den Manager nicht installierbar

### ISSUE THREAD

**Issue by hinzke** [slashworks/contao-starter-bundle#5]
Es wird folgende Meldung ausgegeben

``$ /usr/local/bin/php7.2.19-cli -q /XXX/web/contao-manager.phar.php composer require slashworks/contao-starter-bundle --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using version ^1.9 for slashworks/contao-starter-bundle
/XXX/contaoModuleTest/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v2.4.3

[7.2MiB/0.20s] Loading composer repositories with package information
[7.6MiB/0.33s] Updating dependencies

An error occurred during resolving process:
Could not load package slashworks/contao-trackingmanager-bundle in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^4.*: Invalid version string "^4.*"

# Cloud Job ID x4znDstgVUK7cyfvvz6AtNtT7mMIJnwoCaJOgbaB0qp9pCjP68foyGvFX6Qicq5WV2hilZy5Hz failed

---

### Der Hintergrundprozess wurde unerwartet beendet ###``

**Comment by cliffparnitzky** [comment]
At least since version 1.9.12 not longer valid
